[features]
seeds = false
skip-lint = false
[programs.devnet]
tic_tac_toe_contract = "2b9zH5CkDZJaydK9EfCfWvixkBqaF69ux2pNbr667rLE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "AkvGvETabq9r8DnN98itYjQ8SvYRYx1aZYo7qZbSCjpg"
solana_version = "1.16.17"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
